config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'
  get :dashboard, to: 'dashboard#index'

  resource :session, only: [:new, :edit, :create, :destroy]

  resources :quiz do
    member do
      put :start
    end
  end

  namespace :admin do
    get :dashboard, to: 'dashboard#index'
    resources :quizzes do
       resource :assign, only: [:new, :create]
    end
    resources :groups
    resources :users do
      resources :results, except: [:edit, :new, :update]
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController

  def index
    @groups = UserGroup.all
    @quizzes = Quiz.all
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index

  end

end

app/views/dashboard/index.html.slim
.col-sm-12.col-md-12.mt20
  h3 #{current_user.name}, ваши задания:

  .col-sm-12.col-md-12
    .panel.panel-success
      .panel-heading Выполненные (#{current_user.quiz_participations.completed.count})
      .panel-body
        ul.list-unstyled
          - current_user.quiz_participations.completed.each do |q|
            li
              = q.quiz.title
              = link_to "результат", quiz_path(q), class: "btn btn-xs btn-default ml20"

    .panel.panel-info
      .panel-heading Новые назначенные (#{current_user.quiz_participations.pending.count})
      .panel-body
        ul.list-unstyled
          - current_user.quiz_participations.pending.each do |q|
            li
              = q.quiz.title
              = link_to "начать тест", start_quiz_path(q), method: :put, class: "btn btn-xs btn-default ml20"

    .panel.panel-warning
      .panel-heading В процессе (#{current_user.quiz_participations.in_process.count})
      .panel-body
        ul.list-unstyled
          - current_user.quiz_participations.in_process.each do |q|
            li
              = q.quiz.title
              = link_to "продолжить тест", edit_quiz_path(q), class: "btn btn-xs btn-default ml20"
              span.ml10.gray вы начали проходить #{I18n.l q.started_at, format: :short}


.col-sm-12.col-md-12.mt20
  hr

  h3 Вы состоите в группах:
  ul.list-unstyled
    - current_user.user_groups.each do |group|
      li= group.title