config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'
  get :dashboard, to: 'dashboard#index'

  resource :session, only: [:new, :edit, :create, :destroy]

  resources :quiz do
    member do
      put :start
    end
  end

  namespace :admin do
    get :dashboard, to: 'dashboard#index'
    resources :quizzes do
       resource :assign, only: [:new, :create]
    end
    resources :groups
    resources :users do
      resources :results, except: [:edit, :new, :update]
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController

  def index
    @groups = UserGroup.all
    @quizzes = Quiz.all
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index

  end

end

app/views/admin/dashboard/index.html.slim
.col-sm-12.col-md-12
  .panel.panel-success
    .panel-heading Группы, участники
    .panel-body
      table.table.table-striped
        tr
          th.col-md-4 Группа
          th.col-md-8 Участники
        - @groups.each do |group|
          tr
            td.bld= group.title
            td
              .pull-right
                = link_to "добавить участника", "#", class: "btn btn-xs btn-info disabled"
              ul.list-unstyled
                - group.users.each do |user|
                  li= link_to "#{user.name} (#{user.email})", edit_admin_user_path(user), title: 'Просмотр и Редактирование участника'
        tr
          td
            = link_to "добавить группу", new_admin_group_path, class: "btn btn-xs btn-info disabled"
          td


  .panel.panel-info
    .panel-heading Задания
    .panel-body
      table.table.table-striped
        tr
          th.col-md-4 Название
          th.col-md-8 Описание
        - @quizzes.each do |q|
          tr
            td.bld #{q.title} (#{q.questions.count})
            td
              .pull-right
                = link_to "назначить", new_admin_quiz_assign_path(q), class: "btn btn-xs btn-success mr10"
                = link_to "редактировать", edit_admin_quiz_path(q), class: "btn btn-xs btn-info mr10"
                = link_to "удалить", admin_quiz_path(q), method: :delete, class: "btn btn-xs btn-danger disabled"
              = q.description
        tr
          td
            = link_to "добавить задание", new_admin_quiz_path, class: "btn btn-xs btn-info"
          td


  .panel.panel-warning
    .panel-heading Результаты заданий
    .panel-body