config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'
  get :dashboard, to: 'dashboard#index'

  resource :session, only: [:new, :edit, :create, :destroy]

  resources :quiz do
    member do
      put :start
    end
  end

  namespace :admin do
    get :dashboard, to: 'dashboard#index'
    resources :quizzes do
       resource :assign, only: [:new, :create]
    end
    resources :groups
    resources :users do
      resources :results, except: [:edit, :new, :update]
    end
  end
end

app/controllers/admin/quizzes_controller.rb
class Admin::QuizzesController < AdminController
  before_action :get_resource, only: [:edit, :update, :destroy]

  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def get_resource
    @resource = Quiz.find(params[:id])
  end
end

app/views/admin/quizzes/edit.html.slim
.col-sm-12.col-md-12
  .panel.panel-success
    .panel-heading
      h5 Редактирование задания
    .panel-body
      = bootstrap_form_for(@resource, url: admin_quiz_path, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f|
        = f.text_field :title, label: 'Название'
        = f.text_area :description, label: 'Описание', rows: 5

        .form-group
          label.col-sm-3.control-label Вопросы задания:
          .col-sm-9
            - @resource.questions.each do |q|
              .panel
                .panel-body
                  strong= q.body
                  ul.list-unstyled
                    - q.responses.each do |r|
                      li
                        - if r.correct?
                          - if q.is_a?(QuestionMultiplyCorrect)
                            input type="checkbox" checked="checked"
                          - else
                            input type="radio" checked="checked"
                        - else
                          - if q.is_a?(QuestionMultiplyCorrect)
                            input type="checkbox"
                          - else
                            input type="radio"

                        span.ml10
                          = r.body



        = f.submit "сохранить", disabled: 'disabled'
        = link_to "отмена", admin_dashboard_path, class: 'btn btn-default col-sm-offset-3'

app/views/admin/quizzes/index.html.slim
.col-md-12.col-sm-12
  h3 TODO

app/views/admin/quizzes/new.html.slim
.col-md-12.col-sm-12
  h3 TODO

app/views/admin/quizzes/view.html.slim
.col-md-12.col-sm-12
  h3 TODO