config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'
  get :dashboard, to: 'dashboard#index'

  resource :session, only: [:new, :edit, :create, :destroy]

  resources :quiz do
    member do
      put :start
    end
  end

  namespace :admin do
    get :dashboard, to: 'dashboard#index'
    resources :quizzes do
       resource :assign, only: [:new, :create]
    end
    resources :groups
    resources :users do
      resources :results, except: [:edit, :new, :update]
    end
  end
end

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta charset="UTF-8"
    title Администрирование Quizzz!
    meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"

    = stylesheet_link_tag bootstrap_css
    = stylesheet_link_tag bootstrap_theme_css
    = stylesheet_link_tag font_awesome_css
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true

    = csrf_meta_tags

    /! HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    /! WARNING: Respond.js doesn't work if you view the page via file://
    /![if lt IE 9]
      | <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      | <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>

  body.container
    .row
      .col-md-1
        h3
          = link_to admin_dashboard_path, title: 'Главная страница администрирования' do
            i.glyphicon.glyphicon-th-large

      - if current_user
        .col-md-4.pull-right.bg-green-yellow.p10.text-right
          span.bld Администратор
          = link_to "Выйти", session_path, method: :delete, class: 'btn btn-sm btn-danger ml10'

    .row
      = flash_messages

      .col-md-12.col-sm-12
        hr

      = yield


    = javascript_include_tag 'application'
    = javascript_include_tag bootstrap_js
    = yield :javascripts

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="UTF-8"
    title Quizzz!
    meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"

    = stylesheet_link_tag bootstrap_css
    = stylesheet_link_tag bootstrap_theme_css
    = stylesheet_link_tag font_awesome_css
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true

    = csrf_meta_tags

    /! HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    /! WARNING: Respond.js doesn't work if you view the page via file://
    /![if lt IE 9]
      | <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      | <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>

  body.container
    .row
      .col-md-1
        h3
          = link_to root_path, title: 'Главная страница' do
            i.glyphicon.glyphicon-th-large

      - if current_user
        .col-md4.pull-right
          = link_to "Выйти", session_path, method: :delete, class: 'btn btn-sm btn-danger mt20'

    .row
      = flash_messages

    .row
      = yield


    = javascript_include_tag 'application'
    = javascript_include_tag bootstrap_js
    = yield :javascripts